namespace Spectra.Engine.Services.Data.Internal.Events.Logger;

/// <summary>
///     Event fired when a log message is generated by the logging system
///     This allows other components to react to log events via the event bus
/// </summary>
public record LogEvent(LogEventData LogData);
